# Generated by Django 4.2.7 on 2023-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newordermodel',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
