# Generated by Django 4.2.7 on 2023-11-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_newordermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
